#include <xdc/std.h>
#include <xdc/runtime/Startup.h>
#include <ti/drivers/GPIO.h>

#include <platforms/hw/tiva/GpioPort.h>
#include <platforms/hw/tiva/GpioPeriph.h>

#include <stdint.h>
#include <stdbool.h>
#include <inc/hw_memmap.h>
#include <driverlib/gpio.h>
#include <driverlib/sysctl.h>

#include "package/internal/Led.xdc.h"

#define LED_OFF (0)
#define LED_ON  (~0)

// Snice can't initialize GPIO_Config in meta domain, have this limit here
#define MAX_LEDS 8

// Globally visible symbol for ti.drivers.GPIO
GPIO_Config GPIO_config[MAX_LEDS];

static GPIO_HWAttrs gpioHWAttrs[MAX_LEDS];

Void Led_setLed(UInt led, Bool on)
{
    GPIO_write(led, on ? LED_ON : LED_OFF);
}

Void Led_pulseLed(UInt led)
{
    Int i = Led_pulseDelayIters;
    Led_setLed(led, TRUE);
    while (i--);
    Led_setLed(led, FALSE);
}

Int Led_Module_startup(Int state)
{
    UInt led;
    const GpioPort_Info *gpioPort;
    const GpioPeriph_Info *gpioPeriph;

    for (led = 0; led < module->gpioPorts.length; ++led) {
        gpioPort = GpioPort_getInfo(module->gpioPorts.elem[led]);
        gpioPeriph = GpioPeriph_getInfo(gpioPort->periph);

        // Looks like this cannot be initialized in meta domain because
        // the GPIO.h header is not the autogenerated module header.
        gpioHWAttrs[led].port = gpioPeriph->base;
        gpioHWAttrs[led].pin = gpioPort->pin;
        gpioHWAttrs[led].direction = GPIO_OUTPUT;

        GPIO_config[led].hwAttrs = &gpioHWAttrs[led];

        SysCtlPeripheralEnable(gpioPeriph->periph);
        GPIOPinTypeGPIOOutput(gpioPeriph->base, gpioPort->pin);
    }

    GPIO_init(); /* Once GPIO_init is called, GPIO_config cannot be changed */

    for (led = 0; led < module->gpioPorts.length; ++led)
        GPIO_write(led, LED_OFF);

    return Startup_DONE;
}
